import os
import dotenv
from langchain_groq import ChatGroq
from pydantic import BaseModel, Field
dotenv.load_dotenv()

groq_api_key=os.getenv("GROQ_API_KEY")

from langchain_core.prompts import ChatPromptTemplate

llm=ChatGroq(groq_api_key=groq_api_key,model_name="qwen/qwen3-32b")

class AnswerGrader(BaseModel):
    '''
    Binary Score for checking whether the answer generated by the LLM actually answers the question or not.
    '''
    binary_score: str = Field(description="Binary score indicating whether the answer actually answers the question or not. Acceptable values are 'yes' or 'no'.")


system = """You are a grader assessing whether an answer addresses / resolves a question \n 
     Give a binary score 'yes' or 'no'. 'Yes' means that the answer resolves the question."""

answer_grade_prompt_template = ChatPromptTemplate.from_messages(
    [
        ("system", system),
        ("user", "User Question: {question}\n\n Generated Answer: {generation}"),
    ]
)

answer_structured_llm_grader = llm.with_structured_output(AnswerGrader)

answer_grader = answer_grade_prompt_template | answer_structured_llm_grader
